DROP TABLE IF EXISTS EMPRUNT;
DROP TABLE IF EXISTS EXEMPLAIRE;
DROP TABLE IF EXISTS OEUVRE;
DROP TABLE IF EXISTS AUTEUR;
DROP TABLE IF EXISTS ADHERENT;


CREATE TABLE IF NOT EXISTS ADHERENT(
	idAdherent INT AUTO_INCREMENT,
	nomAdherent VARCHAR(30),
	adresse VARCHAR(30),
	datePaiement date,
	PRIMARY KEY(idAdherent)
);

CREATE TABLE IF NOT EXISTS AUTEUR(
	idAuteur INT AUTO_INCREMENT,
	nomAuteur VARCHAR (30),
	prenomAuteur VARCHAR (30),
	PRIMARY KEY(idAuteur)
);

CREATE TABLE IF NOT EXISTS OEUVRE(
	noOeuvre INT AUTO_INCREMENT,
	titre VARCHAR(30),
	dateParution date,
	idAuteur INT,
	CONSTRAINT fk_idAuteur_AUTEUR_OEUVRE
		FOREIGN KEY(idAuteur) REFERENCES AUTEUR(idAuteur) ON DELETE CASCADE,
	PRIMARY KEY(noOeuvre)

);
CREATE TABLE IF NOT EXISTS EXEMPLAIRE(
	noExemplaire INT AUTO_INCREMENT,
	etat VARCHAR(30),
	dateAchat date,
	prix NUMERIC(4,2),
	noOeuvre INT,
	CONSTRAINT fk_noOeuvre_OEUVRE_EXEMPLAIRE
		FOREIGN KEY(noOeuvre) REFERENCES OEUVRE(noOeuvre)ON DELETE CASCADE,
	PRIMARY KEY(noExemplaire)
);

CREATE TABLE IF NOT EXISTS EMPRUNT(
	idAdherent INT,
	noExemplaire INT,
	dateEmprunt date,
	dateRendu date,
	CONSTRAINT fk_idAdherent_ADHERENT_EMPRUNT
		FOREIGN KEY(idAdherent) REFERENCES ADHERENT(idAdherent)ON DELETE CASCADE,
	CONSTRAINT fk_noExemplaire_EXEMPLAIRE_EMPRUNT
		FOREIGN KEY(noExemplaire) REFERENCES EXEMPLAIRE(noExemplaire)ON DELETE CASCADE,
	PRIMARY KEY(idAdherent, noExemplaire,dateEmprunt)
);


LOAD DATA LOCAL INFILE '../donnees/ADHERENT.csv' INTO TABLE ADHERENT CHARACTER SET utf8
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '../donnees/AUTEUR.csv' INTO TABLE AUTEUR CHARACTER SET utf8
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '../donnees/OEUVRE.csv' INTO TABLE OEUVRE CHARACTER SET utf8
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '../donnees/EXEMPLAIRE.csv' INTO TABLE EXEMPLAIRE CHARACTER SET utf8
FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE '../donnees/EMPRUNT.csv' INTO TABLE EMPRUNT CHARACTER SET utf8
FIELDS TERMINATED BY ',';


UPDATE EMPRUNT SET dateRendu = NULL WHERE CAST(dateRendu AS CHAR(10))='0000-00-00';
UPDATE OEUVRE SET dateParution = NULL WHERE CAST(dateParution AS CHAR(10))='0000-00-00';
